---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: Applications/ansible-controller
  type: udm.Application
  lastVersion: 1.0.0
  children:
  - name: 1.0.0
    type: udm.ProvisioningPackage
    deployables:
    - name: ansible-instance
      type: aws.ec2.InstanceSpec
      boundTemplates:
      - Applications/ansible-controller/1.0.0/ansible-host-template
      provisioners:
      - name: ansible-setup
        type: script.provisioner.Script
        hostTemplate: Applications/ansible-controller/1.0.0/ansible-host-template
        file: !file "artifacts/Applications/ansible-controller/1.0.0/ansible-instance/ansible-setup/provision_ansible.sh"
      instanceName: ansible-controller-instance
      amiId: ami-08c757228751c5335
      region: eu-west-3
      securityGroup:
      - Name:ansible-controller-sg
      instanceType: t2.micro
      keyName: myansible-keypair
    - name: ansible-controller-sg
      type: aws.vpc.SecurityGroupSpec
      securityGroupName: ansible-controller-sg
      description: ssh-security (HTTP/SSH)
      region: eu-west-3
      inboundRules:
      - name: ssh
        type: aws.vpc.SecurityGroupInboundRuleSpec
        protocol: TCP
        portRange: "22"
        source: 0.0.0.0/0
    - name: ansible-controller-kp
      type: aws.ec2.KeyPairSpec
      keyPairName: myansible-keypair
      region: eu-west-3
      pemFilePath: ssh-keypairs/myansible-keypair.pem
    templates:
    - name: ansible-host-template
      type: template.overthere.SshHost
      instanceName: ansible-controller-{{%instanceId%}}-host
      childTemplates:
      - name: ansible-controler-template
        type: template.ansible.Controller
        instanceName: defaultAnsibleController
        ansiblePlaybookPath: /usr/bin/ansible-playbook
        ansibleGalaxyPath: /usr/bin/ansible-galaxy
      tags:
      - ansible_roles_not_applied
      os: UNIX
      connectionType: SUDO
      address: '{{%publicHostname%}}'
      username: ubuntu
      privateKeyFile: ssh-keypairs/myansible-keypair.pem
      sudoUsername: root
