---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: Applications/provision-calculator
  type: udm.Application
  lastVersion: 0.0.12
  children:
  - name: 0.0.12
    type: udm.DeploymentPackage
    orchestrator:
      - parallel-by-container
    deployables:
    - name: tomcat
      type: ansible.RolesSpec
      includeDevOpsAsCodeTask: True
      scanPlaceholders: False
      file: !file "artifacts/provision-calculator/0.0.12/roles_frontend"
      tags:
      - frontend
      roles:
      - tomcat8
      variables:
        public_key_path: |-
          /Users/bmoussaud/Workspace/xebialabs-community/xld-terraform-enterprise-plugin/xebialabs/artifacts/keypairs/id_rsa.pub
    - name: bdd
      type: ansible.RolesSpec
      scanPlaceholders: False
      includeDevOpsAsCodeTask: True
      file: !file "artifacts/provision-calculator/0.0.12/roles_backend"
      tags:
      - backend
      roles:
      - mysql
