---
apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
- directory: Infrastructure/defaults
  children:
  - name: localhost
    type: overthere.LocalHost
    os: UNIX
    children:
    - name: defaultAnsibleController
      type: ansible.Controller
