language: java
before_install:
  - openssl aes-256-cbc -K $encrypted_4e891cdfdb85_key -iv $encrypted_4e891cdfdb85_iv
    -in deploy_key.enc -out /tmp/deploy_key -d
  - eval "$(ssh-agent -s)"
  - echo -e "Host $DIST_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - chmod 600 /tmp/deploy_key
  - ssh-add /tmp/deploy_key
script: "./buildViaTravis.sh"
deploy:
  - provider: releases
    api_key:
      secure: ndaCS8+IuxNwVuRxUjBnAlNz0UOO/5ynsR8V/Yku+mTvEYegoSojcSnLJGTounvxcM0r/vHhzm5MBBBZbo19q36CalhrcsP7uoorhz40igUr32dwsKU2WxH3BvnOeXR58ArZnG0n6lxUKi7MI9nmgUTq/R4x/NADvpSvO+gZp5E7b80gL/G1x0Dg77vSmz8CGKr5KAwWW+nFeHsI+3hNcnl3ade6gBGOZIS3SDu6Z3QSURaDxBtCCA31Yf/hQedhbkde1TRvRZ8TFpJmRnJ3zopa3e51V6XG27k8YEl0KTeIM94wNtMBAPkalp8Tnz4aVYXJJ1kZ5Bmq+egOr7LhUSUmz+K98Dw0k5+i35onoQvk+GuZgCoJq82np9PstIqRMyUZaLlMFf6EU60MfWSUhHFMWa0YVGsdSebvbSICEG/Ekrlqu4OvZBNy+nGwBYxC+aIIgDKgDVVMr7wT4M7/cvJ46gQHSJmk6gIr+LeDhPHR2fIXskPlFG5vouckQLvB8avupe2Op597UdGwLXVNGzgxlCj4e0T1LUu0mDNrfhFLY2xbacZvBVFNpXFd6YFzf8jFdouQiYQOspyY8tgmUR/yNIZ/yyftEpinoLfnzNDp6RtdEFjBUpNpo1kakHMhvwEMu5OdkMi3zrsx4uYLc/joXUbXZv4o/ZT+AmI+6T8=
    file_glob: true
    file: build/distributions/*
    skip_cleanup: true
    edge: true
    on:
      all_branches: true
      tags: true
      repo: xebialabs-community/xld-terraform-enterprise-plugin
  - provider: script
    skip_cleanup: true
    script: rsync --update -raz -i $TRAVIS_BUILD_DIR/build/libs/*.jar $DIST_USER@$DIST_HOST:$DIST_PATH/${TRAVIS_REPO_SLUG#*/}/
    on:
      all_branches: true
      tags: true
      repo: xebialabs-community/xld-terraform-enterprise-plugin
