language: java
sudo: false
deploy:
  provider: releases
  api_key:
    secure: ndaCS8+IuxNwVuRxUjBnAlNz0UOO/5ynsR8V/Yku+mTvEYegoSojcSnLJGTounvxcM0r/vHhzm5MBBBZbo19q36CalhrcsP7uoorhz40igUr32dwsKU2WxH3BvnOeXR58ArZnG0n6lxUKi7MI9nmgUTq/R4x/NADvpSvO+gZp5E7b80gL/G1x0Dg77vSmz8CGKr5KAwWW+nFeHsI+3hNcnl3ade6gBGOZIS3SDu6Z3QSURaDxBtCCA31Yf/hQedhbkde1TRvRZ8TFpJmRnJ3zopa3e51V6XG27k8YEl0KTeIM94wNtMBAPkalp8Tnz4aVYXJJ1kZ5Bmq+egOr7LhUSUmz+K98Dw0k5+i35onoQvk+GuZgCoJq82np9PstIqRMyUZaLlMFf6EU60MfWSUhHFMWa0YVGsdSebvbSICEG/Ekrlqu4OvZBNy+nGwBYxC+aIIgDKgDVVMr7wT4M7/cvJ46gQHSJmk6gIr+LeDhPHR2fIXskPlFG5vouckQLvB8avupe2Op597UdGwLXVNGzgxlCj4e0T1LUu0mDNrfhFLY2xbacZvBVFNpXFd6YFzf8jFdouQiYQOspyY8tgmUR/yNIZ/yyftEpinoLfnzNDp6RtdEFjBUpNpo1kakHMhvwEMu5OdkMi3zrsx4uYLc/joXUbXZv4o/ZT+AmI+6T8=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    repo: xebialabs-community/xld-ansible-step-plugin
    all_branches: true
    tags: true
notifications:
  slack:
    secure: tZsdYLSKo/lr9Eio7I3c9Se+Vh18GS3jD8e2iPWrNvAc0Da4A714AsYpfunkmJtbzR7VlPwU5nG1+SQff/HrKFdZfKpoBy+/junCVXyGcfgnzjRWQVMPj18c6+/9wZFQVUIH8E5+fytc3Vfw5ZVmxbJXho48SoFjmUHbQnWb+2ppHB4wmc6zK9id9ccLunvxY5pCeME6+VfJh4cB2y6nPFrtTj4b12Vd7rBW92LPP1vl4UnSTqTQrRM0vg61pVY83SVl6hd41Vboxf1blEiUUp6UW4omdufzt5/3EqUymgYfLNVH8+U1rvs6RzZMM4ZZqo6Vj64LAbEJZH3qi1KtKzsgZ3w9a0h+oMaFaANxqOlpdBlaw3V+8RecVi7BfLpxLhcjD0DpBXA8PdT1Rgs5MyaNhBSCpCoGt923+c8M7azqkv2zOiw6wt4xLmDe5gSeZegDViFY0juew3NMQTVJuje8Nsp8TLiKv/QyLrE1tqbwfayHPRQTE5a+Q0klXDxZRiEozj573oBFdRw1YAQy/cGSo++bBonXwku7UhnGVo8AVfzra0ZTJIw3TkKZuwcW9ltG5+pUdsNwXCyB7P4gYQUi2tmwFhji7DJlZmLC46x9RzQ4X4nRNiB5wfIngSLhQMVZMbwLD1cGB7dUD+gR8aUmdAsjxzrNUhK4Not+hT0=
