language: java
sudo: false
deploy:
  provider: releases
  api_key:
    secure: ndaCS8+IuxNwVuRxUjBnAlNz0UOO/5ynsR8V/Yku+mTvEYegoSojcSnLJGTounvxcM0r/vHhzm5MBBBZbo19q36CalhrcsP7uoorhz40igUr32dwsKU2WxH3BvnOeXR58ArZnG0n6lxUKi7MI9nmgUTq/R4x/NADvpSvO+gZp5E7b80gL/G1x0Dg77vSmz8CGKr5KAwWW+nFeHsI+3hNcnl3ade6gBGOZIS3SDu6Z3QSURaDxBtCCA31Yf/hQedhbkde1TRvRZ8TFpJmRnJ3zopa3e51V6XG27k8YEl0KTeIM94wNtMBAPkalp8Tnz4aVYXJJ1kZ5Bmq+egOr7LhUSUmz+K98Dw0k5+i35onoQvk+GuZgCoJq82np9PstIqRMyUZaLlMFf6EU60MfWSUhHFMWa0YVGsdSebvbSICEG/Ekrlqu4OvZBNy+nGwBYxC+aIIgDKgDVVMr7wT4M7/cvJ46gQHSJmk6gIr+LeDhPHR2fIXskPlFG5vouckQLvB8avupe2Op597UdGwLXVNGzgxlCj4e0T1LUu0mDNrfhFLY2xbacZvBVFNpXFd6YFzf8jFdouQiYQOspyY8tgmUR/yNIZ/yyftEpinoLfnzNDp6RtdEFjBUpNpo1kakHMhvwEMu5OdkMi3zrsx4uYLc/joXUbXZv4o/ZT+AmI+6T8=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    repo: xebialabs-community/xld-ansible-step-plugin
    all_branches: true
    tags: true
notifications:
  hipchat:
    rooms:
      secure: OM5c6Ch5FJ0PfB4L3jUSq6ex2WI253b6zj8794hpcqkZDVBw5dv+AOPrYJaPgVNmwBuK2szptJQCZ5jDhBlETc+HPpTHKiAsqPCWxu55X89uGNB2Iy20LzmVotJ5n83/rUSp8dGLWKqNu5RYlMHpnxqiWrH9Bx06UPYL9vMDjBTSa6Gn/OwF9sDa2K4C9LWMP2OXAgwCurk0u7qeJJ0VT1+Rx2G+ztzrFe4SlO/Ha8Nk1HAAbLq8tatA4n3Y6e6j/ArGZrKR9JwzgxWPZSxsDh63D5Kojyo1kB1qAzPLe76D+KVwNe/ecnOdtIDinpjkuphLtkjRDygYQOxr/3eDAV0cwkNZVrYFbiJAQ4yFKB9kD4vI9QZkEfGlK6jo2LQZ1s0CgTFsSiDYCVUltyOjehyhmYm11h3J7MamL4kRBetFy7PRVSmnenp0u6IOovBZS6VI0T495gw7E8Pf/SLTaImWhL3YmPQgH1e55E4aByQPmghnHNQEtyPVk3oDMR+GkTZvWtAdCAJIcCUST/lnww/IM+X7MMCRhmE6XVHcX5LngGlb2I6CyqjvNBykKaDpR65E+6EtIaQvsA5J0STo6DF+DQTFgFHHjZ6/unQyPRf3fDFdfTCgKd8713kgDBffLXis6xoYaTY75eyzCwWKi+Zzlg6vz05i3GdGMFC4K5Q=
